export const GET_ALL_POST = "GET_ALL_POST";
export const DATA_LOADING = "DATA_LOADING";
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';